currency:
  crowns-per-shilling: 100
  shillings-per-penny: 100
  crown-name: Crowns
  shilling-name: Shillings
  penny-name: Pennies

player-data:
  starting-balance: 500

inbox:
  enabled: true
  max-per-player: 50
  live-chat-notifications: true

resource-pack:
  enabled: true
  required: true
  version: 1.8.1
  url: "https://github.com/All-The-Game-Servers/CrownsSuite/releases/download/resource-pack-1.8.1/CrownsSuite-ResourcePack-1.8.1.zip"
  download-url: "https://github.com/All-The-Game-Servers/CrownsSuite/releases/download/resource-pack-1.8.1/CrownsSuite-ResourcePack-1.8.1.zip"
  github-page-url: "https://github.com/All-The-Game-Servers/CrownsSuite/releases"
  sha1: "f22e011db601359a46bb0a006b655e4dcafb771e"
  allow-client-prompt-with-valhalla: true
  prompt: Lowlight SMP requires the Crowns Suite resource pack for custom items and menus.
  github:
    owner: All-The-Game-Servers
    repo: CrownsSuite
    release-tag: latest
    asset-pattern: CrownsSuite-ResourcePack-*.zip
    sha1-pattern: CrownsSuite-ResourcePack-*.sha1
    resolved-release-tag: ''
    last-refresh: ''
