currency:
  crowns-per-shilling: 100
  shillings-per-penny: 100
  crown-name: Crowns
  shilling-name: Shillings
  penny-name: Pennies

player-data:
  starting-balance: 500

inbox:
  enabled: true
  max-per-player: 50
  live-chat-notifications: true

resource-pack:
  enabled: true
  version: 1.2.0
  url: "https://raw.githubusercontent.com/All-The-Game-Servers/CrownsSuite/master/downloads/CrownsSuite-ResourcePack-1.2.0.zip"
  download-url: "https://raw.githubusercontent.com/All-The-Game-Servers/CrownsSuite/master/downloads/CrownsSuite-ResourcePack-1.2.0.zip"
  github-page-url: "https://github.com/All-The-Game-Servers/CrownsSuite/tree/master/downloads"
  sha1: "8939f46d7d8fcfacefe0bacfa47776a2f9aad645"
  allow-client-prompt-with-valhalla: false
  prompt: Lowlight SMP uses the Crowns Suite resource pack for custom items and menus.
