dependencies {
    implementation project(':api')
}

sourceSets {
    main {
        java {
            exclude 'com/xkstudios/crowns/Currency.java'
            exclude 'com/xkstudios/crowns/command/CrownsCommand.java'
            exclude 'com/xkstudios/crowns/BountyManager.java'
            exclude 'com/xkstudios/crowns/listener/PlayerListener.java'
            exclude 'com/xkstudios/crowns/listener/ShopListener.java'
            exclude 'com/xkstudios/crowns/market/ChestShopData.java'
            exclude 'com/xkstudios/crowns/market/ChestShopManager.java'
            exclude 'com/xkstudios/crowns/market/MarketStall.java'
            exclude 'com/xkstudios/crowns/market/MarketStallListing.java'
            exclude 'com/xkstudios/crowns/market/MarketStallOverflowItem.java'
            exclude 'com/xkstudios/crowns/market/StallManager.java'
        }
    }
}

jar {
    archiveBaseName = 'CrownsEconomy'
}
