#!/usr/bin/env bash
# ==============================================================
#  Minecraft Java — Instance Startup Script
#  Generated by ATGS. This file is copied into each instance.
#
#  Environment variables (set by the runner container):
#    MIN_RAM, MAX_RAM, EULA, RCON_PORT, RCON_PASSWORD
#
#  The VARIANT marker below is replaced during install.
# ==============================================================
set -e
cd /instance

# ── JVM Flags (Aikar's optimized G1GC flags) ─────────────────
PROFILE="${PERF_PROFILE:-balanced}"
JAVA_EXTRA="${JAVA_EXTRA_FLAGS:-}"

COMMON_FLAGS=(
    -Xms${MIN_RAM:-1G}
    -Xmx${MAX_RAM:-2G}
    -Djava.awt.headless=true
    -XX:+UseG1GC
    -XX:+ParallelRefProcEnabled
    -XX:+DisableExplicitGC
    -XX:+AlwaysPreTouch
    -XX:+PerfDisableSharedMem
)

case "$PROFILE" in
    low-memory)
        PROFILE_FLAGS=(
            -XX:MaxGCPauseMillis=250
            -XX:G1HeapRegionSize=4M
            -XX:G1ReservePercent=15
            -XX:InitiatingHeapOccupancyPercent=25
        )
        ;;
    high-performance)
        PROFILE_FLAGS=(
            -XX:MaxGCPauseMillis=120
            -XX:+UnlockExperimentalVMOptions
            -XX:G1NewSizePercent=35
            -XX:G1MaxNewSizePercent=45
            -XX:G1HeapRegionSize=8M
            -XX:G1ReservePercent=20
            -XX:G1HeapWastePercent=5
            -XX:G1MixedGCCountTarget=4
            -XX:InitiatingHeapOccupancyPercent=15
            -XX:G1MixedGCLiveThresholdPercent=90
            -XX:SurvivorRatio=32
            -XX:MaxTenuringThreshold=1
        )
        ;;
    *)
        PROFILE_FLAGS=(
            -XX:MaxGCPauseMillis=180
            -XX:+UnlockExperimentalVMOptions
            -XX:G1HeapRegionSize=8M
            -XX:G1ReservePercent=20
            -XX:G1HeapWastePercent=5
            -XX:InitiatingHeapOccupancyPercent=20
        )
        ;;
esac

JVM_FLAGS=("${COMMON_FLAGS[@]}" "${PROFILE_FLAGS[@]}")
if [ -n "$JAVA_EXTRA" ]; then
    # shellcheck disable=SC2206
    EXTRA_FLAGS=($JAVA_EXTRA)
    JVM_FLAGS+=("${EXTRA_FLAGS[@]}")
fi

# ── Detect which jar to launch ───────────────────────────────
if [ -f fabric-server-launch.jar ]; then
    JAR="fabric-server-launch.jar"
elif [ -f run.sh ] && grep -q forge run.sh 2>/dev/null; then
    # Forge 1.17+ uses its own run.sh
    echo "[ATGS] Launching via Forge run.sh..."
    exec bash run.sh
elif [ -f server.jar ]; then
    JAR="server.jar"
else
    # Search for any forge jar
    JAR=$(find /instance -maxdepth 1 -name 'forge-*.jar' ! -name '*installer*' -type f | head -1)
    if [ -z "$JAR" ]; then
        echo "[ATGS] ERROR: No server jar found in /instance/"
        ls -la /instance/
        sleep infinity
    fi
fi

echo "[ATGS] Profile: ${PROFILE}"
echo "[ATGS] Launching: java ${JVM_FLAGS[*]} -jar ${JAR} --nogui"
exec java "${JVM_FLAGS[@]}" -jar "$JAR" --nogui
