// Task protocol. Builds on protocol.go.
//
// Design notes:
//
//   - Tasks are typed. There is no "generic exec" task. Each kind has a
//     payload schema validated on both sides. This is the difference between
//     "remote management" and "remote shell."
//
//   - Tasks flow Central -> Keeper over the control channel. The Keeper
//     replies with progress frames (optional) and exactly one result frame.
//     A task with no result frame after TaskTimeout is considered failed
//     and will be retried or surfaced to the operator.
//
//   - Task envelopes carry a CorrelationID matching the TaskDispatch's ID,
//     so multiple concurrent tasks on the same Keeper can be demultiplexed
//     by the Central-side tracker.
//
//   - Signing: production builds should sign TaskDispatch payloads with a
//     Central-held key that Keepers pin. Phase 2 defines the Signature
//     field but leaves it empty; Phase 7 hardening populates it. The schema
//     is here now so we don't break the wire format when we turn it on.
package protocol

import (
	"encoding/json"
	"time"
)

// TaskKind enumerates every operation Central can ask a Keeper to perform.
// Adding a new kind is a protocol change; bump ProtocolVersion.
type TaskKind string

const (
	// Instance lifecycle.
	TaskInstanceCreate TaskKind = "instance.create"
	TaskInstanceStart  TaskKind = "instance.start"
	TaskInstanceStop   TaskKind = "instance.stop"
	TaskInstanceDelete TaskKind = "instance.delete"

	// Observation.
	TaskInstanceLogsTail     TaskKind = "instance.logs.tail"
	TaskInstanceConsoleWrite TaskKind = "instance.console.write"
	TaskInstanceStatus       TaskKind = "instance.status"
	TaskKeeperResourcesSnap  TaskKind = "keeper.resources.snapshot"
	TaskInstanceFileList     TaskKind = "instance.file.list"
	TaskInstanceFileRead     TaskKind = "instance.file.read"
	TaskInstanceFileWrite    TaskKind = "instance.file.write"
	TaskInstanceFileDelete   TaskKind = "instance.file.delete"
	TaskInstanceFileRename   TaskKind = "instance.file.rename"

	// Phase 7: remote kill switch. When the Keeper receives this it wipes
	// its on-disk identity and exits. Central also revokes the cert in its
	// CRL so a later reconnect attempt with stale files fails at TLS.
	TaskKeeperRevoke TaskKind = "keeper.revoke"
)

// KeeperRevokePayload carries the reason for the kill. Logged by the Keeper
// before it exits so the operator (reading local logs) knows why.
type KeeperRevokePayload struct {
	Reason string `json:"reason"`
	Actor  string `json:"actor,omitempty"` // progenitor ID if available
}

// TaskStatus is the lifecycle state of a task on the Central side.
type TaskStatus string

const (
	TaskStatusQueued     TaskStatus = "queued"
	TaskStatusDispatched TaskStatus = "dispatched" // sent to keeper, awaiting ack
	TaskStatusRunning    TaskStatus = "running"    // keeper acked, in progress
	TaskStatusSucceeded  TaskStatus = "succeeded"
	TaskStatusFailed     TaskStatus = "failed"
	TaskStatusTimedOut   TaskStatus = "timed_out"
)

// TaskDispatch is the Envelope.Data for KindTaskDispatch.
//
// TaskID is generated by Central and used as the correlation ID for
// every reply from the Keeper (ack, progress, result).
type TaskDispatch struct {
	TaskID           string          `json:"task_id"`
	Kind             TaskKind        `json:"kind"`
	Payload          json.RawMessage `json:"payload"` // kind-specific; see payload structs below
	DispatchedAtUnix int64           `json:"dispatched_at_unix"`
	TimeoutSecs      int             `json:"timeout_secs"` // hard ceiling; keeper should abort if exceeded

	// Signature is reserved for Phase 7. When populated, it is the base64
	// signature of a canonical encoding of (TaskID, Kind, Payload, DispatchedAtUnix)
	// using a Central-held signing key. Keepers will verify this against a
	// pinned public key before executing.
	Signature string `json:"signature,omitempty"`
}

// TaskAck is the Keeper's first reply after receiving a TaskDispatch.
// Sending an ack moves the task from Dispatched to Running on Central.
type TaskAck struct {
	TaskID         string `json:"task_id"`
	AcceptedAtUnix int64  `json:"accepted_at_unix"`
}

// TaskProgress is an optional stream of updates from the Keeper during task
// execution. Not every task emits progress; long-running ones (install,
// backup) will.
type TaskProgress struct {
	TaskID  string  `json:"task_id"`
	Percent float64 `json:"percent,omitempty"` // 0-100
	Message string  `json:"message,omitempty"`
}

// TaskResult is the final reply. Exactly one per task.
type TaskResult struct {
	TaskID          string          `json:"task_id"`
	Success         bool            `json:"success"`
	ErrorCode       string          `json:"error_code,omitempty"` // machine-readable
	ErrorMessage    string          `json:"error_message,omitempty"`
	Result          json.RawMessage `json:"result,omitempty"` // kind-specific success payload
	CompletedAtUnix int64           `json:"completed_at_unix"`
}

// --- Payload types for each TaskKind ---

// InstanceCreatePayload creates a new container instance on the Keeper.
//
// EggID references a named egg (server template) the Keeper has locally.
// Env overrides default env vars from the egg. PortMappings declares which
// container ports should be exposed to the relay in Phase 3; for Phase 2
// they're published to the Keeper's host directly (127.0.0.1 only).
type InstanceCreatePayload struct {
	InstanceID     string            `json:"instance_id"` // Central-generated UUID
	EggID          string            `json:"egg_id"`      // e.g. "minecraft-java-paper"
	DisplayName    string            `json:"display_name"`
	Env            map[string]string `json:"env,omitempty"`
	ResourceLimits ResourceLimits    `json:"resource_limits"`
	PortMappings   []PortMapping     `json:"port_mappings,omitempty"`
}

// ResourceLimits caps what a single instance can consume on a Keeper.
// Memory in bytes, CPU in shares (1024 = one full core).
type ResourceLimits struct {
	MemoryBytes    uint64 `json:"memory_bytes"`
	CPUShares      int64  `json:"cpu_shares"`
	DiskQuotaBytes uint64 `json:"disk_quota_bytes,omitempty"` // advisory in phase 2
}

// PortMapping describes one TCP port the instance exposes.
type PortMapping struct {
	ContainerPort int    `json:"container_port"`
	HostPort      int    `json:"host_port"` // Keeper-local
	Protocol      string `json:"protocol"`  // "tcp" or "udp"
}

// InstanceCreateResult returned on success.
type InstanceCreateResult struct {
	InstanceID  string `json:"instance_id"`
	ContainerID string `json:"container_id"`
	HostPort    int    `json:"host_port"` // TCP port Docker bound on the keeper host; 0 if no port mapped
}

// InstanceStartResult is returned on successful instance.start. HostPort is
// re-detected after ContainerStart because Docker does not populate port
// bindings in ContainerInspect until the container actually starts. Central
// uses this to fire a routing upsert if the instance has a hostname.
type InstanceStartResult struct {
	InstanceID string `json:"instance_id"`
	HostPort   int    `json:"host_port"`
}

// InstanceStartPayload / InstanceStopPayload / InstanceDeletePayload share
// a simple shape: just an instance ID.
type InstanceIDPayload struct {
	InstanceID string `json:"instance_id"`
}

// InstanceStatusResult describes the current state of an instance.
type InstanceStatusResult struct {
	InstanceID    string `json:"instance_id"`
	ContainerID   string `json:"container_id"`
	State         string `json:"state"` // created, running, stopped, error
	StartedAtUnix int64  `json:"started_at_unix,omitempty"`
	ExitCode      *int   `json:"exit_code,omitempty"`
}

// InstanceLogsTailPayload requests a log window from an instance.
// In Phase 2 we return the last N lines as a single result frame. A
// streaming variant using progress frames can be added later.
type InstanceLogsTailPayload struct {
	InstanceID string `json:"instance_id"`
	Lines      int    `json:"lines"` // max lines to return; 0 means "reasonable default"
}

// InstanceLogsTailResult is what comes back.
type InstanceLogsTailResult struct {
	InstanceID string   `json:"instance_id"`
	Lines      []string `json:"lines"`
	Truncated  bool     `json:"truncated"` // true if buffer was larger than requested
}

// InstanceConsoleWritePayload sends a single console line to an instance's
// stdin. This is intentionally narrow: no shell, no file access, just the
// running server console.
type InstanceConsoleWritePayload struct {
	InstanceID string `json:"instance_id"`
	Input      string `json:"input"`
}

type InstanceConsoleWriteResult struct {
	InstanceID string `json:"instance_id"`
	Accepted   bool   `json:"accepted"`
}

// KeeperResourcesSnapshotResult carries the same fields as ResourcesReport
// but is request-response rather than periodic. Used for on-demand refresh.
type KeeperResourcesSnapshotResult struct {
	Resources ResourcesReport `json:"resources"`
}

// --- Defaults and helpers ---

// DefaultTaskTimeout is applied when a task doesn't specify one.
const DefaultTaskTimeout = 60 * time.Second
