// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {client} from '../models';

export function Connect(arg1:main.ConnectionConfig):Promise<void>;

export function CreateBackup(arg1:string,arg2:client.CreateBackupRequest):Promise<client.CreateBackupResponse>;

export function CreateInstance(arg1:string,arg2:client.CreateInstanceRequest):Promise<client.CreateInstanceResponse>;

export function CreateSchedule(arg1:string,arg2:client.CreateScheduleRequest):Promise<client.Schedule>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DeleteInstance(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function IsConnected():Promise<boolean>;

export function ListAllInstances():Promise<Array<client.Instance>>;

export function ListAllSchedules():Promise<Array<client.Schedule>>;

export function ListBackupsForInstance(arg1:string):Promise<Array<client.Backup>>;

export function ListKeepers():Promise<Array<client.Keeper>>;

export function MintEnrollmentToken(arg1:string):Promise<client.MintTokenResponse>;

export function RestoreBackup(arg1:string,arg2:string):Promise<void>;

export function SavedConnection():Promise<main.ConnectionConfig>;

export function StartInstance(arg1:string):Promise<void>;

export function StopInstance(arg1:string):Promise<void>;

export function Whoami():Promise<client.WhoamiResponse>;
