// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateBackup(arg1, arg2) {
  return window['go']['main']['App']['CreateBackup'](arg1, arg2);
}

export function CreateInstance(arg1, arg2) {
  return window['go']['main']['App']['CreateInstance'](arg1, arg2);
}

export function CreateSchedule(arg1, arg2) {
  return window['go']['main']['App']['CreateSchedule'](arg1, arg2);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function ListAllInstances() {
  return window['go']['main']['App']['ListAllInstances']();
}

export function ListAllSchedules() {
  return window['go']['main']['App']['ListAllSchedules']();
}

export function ListBackupsForInstance(arg1) {
  return window['go']['main']['App']['ListBackupsForInstance'](arg1);
}

export function ListKeepers() {
  return window['go']['main']['App']['ListKeepers']();
}

export function MintEnrollmentToken(arg1) {
  return window['go']['main']['App']['MintEnrollmentToken'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2);
}

export function SavedConnection() {
  return window['go']['main']['App']['SavedConnection']();
}

export function StartInstance(arg1) {
  return window['go']['main']['App']['StartInstance'](arg1);
}

export function StopInstance(arg1) {
  return window['go']['main']['App']['StopInstance'](arg1);
}

export function Whoami() {
  return window['go']['main']['App']['Whoami']();
}
